#include<dos.h>
#include<stdio.h>
#include<conio.h>
void main()
{
float a,b,c,d,e,f,g;
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");

a=440;   //these are the musical note's signal frequency 
b=496;   //these frequencies will be the ones that the microcontroller will play...since we use turbo C, i used <dos.h> command to play these freq. 
c=524;   //You will hear dos sounds like in the game "Dangerous DAVE"
d=586;
e=329;
g=392;

//jingle bells
printf("\n\n\n\n\t\t\tJin-");
sound(b);delay(200);nosound();delay(50);		//sound() will play the allocated frequency and nosound() will give u a empty sound...so basically nosound() is same as sound(0)
printf("gle");				// delay(200) means 200ms delay....this one i fixed based on music notations because i learnt music. If you do not know, then seek
sound(b);delay(200);nosound();delay(50);		//someone's help to read them
printf(" Bells,");
sound(b);delay(450);nosound();delay(50);
printf(" Jin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(b);delay(200);nosound();delay(50);
printf(" Bells");
sound(b);delay(450);nosound();delay(50);
printf("\n\n\t\t\tJin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(d);delay(200);nosound();delay(50);
printf(" All");
sound(g);delay(325);nosound();delay(50);
printf(" the");
sound(a);delay(75);nosound();delay(50);
printf(" Way");
sound(b);delay(950);nosound();delay(50);
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tOh!");
sound(c);delay(200);nosound();delay(50);
printf(" What");
sound(c);delay(200);nosound();delay(50);
printf(" Fun!");
sound(c);delay(325);nosound();delay(50);
printf(" It");
sound(c);delay(75);nosound();delay(50);
printf(" Is");
sound(b);delay(200);nosound();delay(50);
printf(" To");
sound(b);delay(200);nosound();delay(50);
printf(" Ride");
sound(b);delay(200);nosound();delay(50);
printf("\n\n\t\t\tIn");
sound(b);delay(75);nosound();delay(50);
printf(" A");
sound(b);delay(75);nosound();delay(50);
printf(" One");
sound(a);delay(200);nosound();delay(50);
printf(" Horse");
sound(a);delay(200);nosound();delay(50);
printf(" Op-");
sound(a);delay(200);nosound();delay(50);
printf("en");
sound(b);delay(200);nosound();delay(50);
printf(" Sleigh,");
sound(a);delay(450);nosound();delay(50);
printf(" Yay!");
sound(d);delay(450);nosound();delay(50);
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tJin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(b);delay(200);nosound();delay(50);
printf(" Bells,");
sound(b);delay(450);nosound();delay(50);
printf(" Jin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(b);delay(200);nosound();delay(50);
printf(" Bells,");
sound(b);delay(450);nosound();delay(50);
printf("\n\n\t\t\tJin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(d);delay(200);nosound();delay(50);
printf(" All");
sound(g);delay(325);nosound();delay(50);
printf(" the");
sound(a);delay(75);nosound();delay(50);
printf(" Way");
sound(b);delay(950);nosound();delay(50);
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tOh!");
sound(c);delay(200);nosound();delay(50);
printf(" What");
sound(c);delay(200);nosound();delay(50);
printf(" Fun!");
sound(c);delay(325);nosound();delay(50);
printf(" It");
sound(c);delay(75);nosound();delay(50);
printf(" Is");
sound(b);delay(200);nosound();delay(50);
printf(" To");
sound(b);delay(200);nosound();delay(50);
printf(" Ride");
sound(b);delay(200);nosound();delay(50);
printf("\n\n\t\t\tIn");
sound(b);delay(75);nosound();delay(50);
printf(" A");
sound(b);delay(75);nosound();delay(50);
printf(" One");
sound(d);delay(200);nosound();delay(50);
printf(" Horse");
sound(d);delay(200);nosound();delay(50);
printf(" Op-");
sound(c);delay(200);nosound();delay(50);
printf("en");
sound(a);delay(200);nosound();delay(50);
printf(" Sleigh.");
sound(g);delay(950);nosound();delay(50);

clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tDash-");
sound(d/2);delay(200);nosound();delay(50);
printf("ing");
sound(b);delay(200);nosound();delay(50);
printf(" Through");
sound(a);delay(200);nosound();delay(50);
printf(" The");
sound(g);delay(200);nosound();delay(50);
printf(" Snow");
sound(d/2);delay(700);nosound();delay(50);
printf("\n\n\t\t\tIn");
sound(d/2);delay(75);nosound();delay(50);
printf(" A");
sound(d/2);delay(75);nosound();delay(50);
printf(" One");
sound(d/2);delay(200);nosound();delay(50);
printf(" Horse");
sound(b);delay(200);nosound();delay(50);
printf(" Op-");
sound(a);delay(200);nosound();delay(50);
printf("en");
sound(g);delay(200);nosound();delay(50);
printf(" Sleigh");
sound(e);delay(950);nosound();delay(50);
printf("\n\n\t\t\tO'er");
sound(e);delay(200);nosound();delay(50);
printf(" The");
sound(c);delay(200);nosound();delay(50);
printf(" Fields");
sound(b);delay(200);nosound();delay(50);
printf(" We");
sound(a);delay(200);nosound();delay(50);
printf(" Go");
sound(d);delay(950);nosound();delay(50);
printf("\n\n\t\t\tLaugh-");
sound(e*2);delay(200);nosound();delay(50);
printf("ing");
sound(d);delay(200);nosound();delay(50);
printf(" All");
sound(c);delay(200);nosound();delay(50);
printf(" The");
sound(a);delay(200);nosound();delay(50);
printf(" Way");
sound(b);delay(975);nosound();delay(25);
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tBells");
sound(d/2);delay(200);nosound();delay(50);
printf(" On");
sound(b);delay(200);nosound();delay(50);
printf(" Bob");
sound(a);delay(200);nosound();delay(50);
printf(" Tails");
sound(g);delay(200);nosound();delay(50);
printf(" Ring");
sound(d/2);delay(700);nosound();delay(50);
sound(d/2);delay(75);nosound();delay(50);
sound(d/2);delay(75);nosound();delay(50);
printf("\n\n\t\t\tMak-");
sound(d/2);delay(200);nosound();delay(50);
printf("ing");
sound(b);delay(200);nosound();delay(50);
printf(" Spi-");
sound(a);delay(200);nosound();delay(50);
printf("rits");
sound(g);delay(200);nosound();delay(50);
printf(" Bright");
sound(e);delay(700);nosound();delay(50);
printf("\n\n\t\t\tWhat");
sound(e);delay(200);nosound();delay(50);
printf(" Fun");
sound(e);delay(200);nosound();delay(50);
printf(" It");
sound(c);delay(200);nosound();delay(50);
printf(" Is");
sound(b);delay(200);nosound();delay(50);
printf(" To");
sound(a);delay(200);nosound();delay(50);
printf(" Laugh");
sound(d);delay(200);nosound();delay(50);
printf(" And");
sound(d);delay(200);nosound();delay(50);
printf(" Sing");
sound(d);delay(200);nosound();delay(50);
printf("\n\n\t\t\tA");
sound(d);delay(200);nosound();delay(50);
printf(" Sleigh-");
sound(e*2);delay(200);nosound();delay(50);
printf("ing");
sound(d);delay(200);nosound();delay(50);
printf(" Song");
sound(c);delay(200);nosound();delay(50);
printf(" To-");
sound(a);delay(200);nosound();delay(50);
printf("night.");
sound(g);delay(450);nosound();delay(50);
printf(" Hey!");
sound(d);delay(450);nosound();delay(50);

clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tJin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(b);delay(200);nosound();delay(50);
printf(" Bells,");
sound(b);delay(450);nosound();delay(50);
printf(" Jin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(b);delay(200);nosound();delay(50);
printf(" Bells");
sound(b);delay(450);nosound();delay(50);
printf("\n\n\t\t\tJin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(d);delay(200);nosound();delay(50);
printf(" All");
sound(g);delay(325);nosound();delay(50);
printf(" the");
sound(a);delay(75);nosound();delay(50);
printf(" Way");
sound(b);delay(950);nosound();delay(50);
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tOh!");
sound(c);delay(200);nosound();delay(50);
printf(" What");
sound(c);delay(200);nosound();delay(50);
printf(" Fun!");
sound(c);delay(325);nosound();delay(50);
printf(" It");
sound(c);delay(75);nosound();delay(50);
printf(" Is");
sound(b);delay(200);nosound();delay(50);
printf(" To");
sound(b);delay(200);nosound();delay(50);
printf(" Ride");
sound(b);delay(200);nosound();delay(50);
printf("\n\n\t\t\tIn");
sound(b);delay(75);nosound();delay(50);
printf(" A");
sound(b);delay(75);nosound();delay(50);
printf(" One");
sound(a);delay(200);nosound();delay(50);
printf(" Horse");
sound(a);delay(200);nosound();delay(50);
printf(" Op-");
sound(a);delay(200);nosound();delay(50);
printf("en");
sound(b);delay(200);nosound();delay(50);
printf(" Sleigh,");
sound(a);delay(450);nosound();delay(50);
printf(" Yay!");
sound(d);delay(450);nosound();delay(50);
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tJin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(b);delay(200);nosound();delay(50);
printf(" Bells,");
sound(b);delay(450);nosound();delay(50);
printf(" Jin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(b);delay(200);nosound();delay(50);
printf(" Bells,");
sound(b);delay(450);nosound();delay(50);
printf("\n\n\t\t\tJin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(d);delay(200);nosound();delay(50);
printf(" All");
sound(g);delay(325);nosound();delay(50);
printf(" the");
sound(a);delay(75);nosound();delay(50);
printf(" Way");
sound(b);delay(950);nosound();delay(50);
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tOh!");
sound(c);delay(200);nosound();delay(50);
printf(" What");
sound(c);delay(200);nosound();delay(50);
printf(" Fun!");
sound(c);delay(325);nosound();delay(50);
printf(" It");
sound(c);delay(75);nosound();delay(50);
printf(" Is");
sound(b);delay(200);nosound();delay(50);
printf(" To");
sound(b);delay(200);nosound();delay(50);
printf(" Ride");
sound(b);delay(200);nosound();delay(50);
printf("\n\n\t\t\tIn");
sound(b);delay(75);nosound();delay(50);
printf(" A");
sound(b);delay(75);nosound();delay(50);
printf(" One");
sound(d);delay(200);nosound();delay(50);
printf(" Horse");
sound(d);delay(200);nosound();delay(50);
printf(" Op-");
sound(c);delay(200);nosound();delay(50);
printf("en");
sound(a);delay(200);nosound();delay(50);
printf(" Sleigh.");
sound(g);delay(725);nosound();delay(25);

clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tA");
sound(d/2);delay(200);nosound();delay(50);
printf(" Day");
sound(d/2);delay(200);nosound();delay(50);
printf(" Or");
sound(b);delay(200);nosound();delay(50);
printf(" Two");
sound(a);delay(200);nosound();delay(50);
printf(" A-");
sound(g);delay(200);nosound();delay(50);
printf("go");
sound(d/2);delay(700);nosound();delay(50);
printf("\n\n\t\t\tI");
sound(d/2);delay(200);nosound();delay(50);
printf(" Thought");
sound(d/2);delay(200);nosound();delay(50);
printf(" I'd");
sound(b);delay(200);nosound();delay(50);
printf(" Take");
sound(a);delay(200);nosound();delay(50);
printf(" A");
sound(g);delay(200);nosound();delay(50);
printf(" Ride");
sound(e);delay(700);nosound();delay(50);
printf("\n\n\t\t\tAnd");
sound(e);delay(200);nosound();delay(50);
printf(" Soon");
sound(e);delay(200);nosound();delay(50);
printf(" Miss");
sound(c);delay(200);nosound();delay(50);
printf(" Fran-");
sound(b);delay(200);nosound();delay(50);
printf("ny");
sound(a);delay(200);nosound();delay(50);
printf(" Bright");
sound(d);delay(700);nosound();delay(50);
printf("\n\n\t\t\tWas");
sound(d);delay(200);nosound();delay(50);
printf(" Seat-");
sound(e*2);delay(200);nosound();delay(50);
printf("ed");
sound(d);delay(200);nosound();delay(50);
printf(" By");
sound(c);delay(200);nosound();delay(50);
printf(" My");
sound(a);delay(200);nosound();delay(50);
printf(" Side");
sound(b);delay(725);nosound();delay(25);
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tThe");
sound(d/2);delay(200);nosound();delay(50);
printf(" Horse");
sound(d/2);delay(200);nosound();delay(50);
printf(" Was");
sound(b);delay(200);nosound();delay(50);
printf(" Lean");
sound(a);delay(200);nosound();delay(50);
printf(" And");
sound(g);delay(200);nosound();delay(50);
printf(" Lank");
sound(d/2);delay(700);nosound();delay(50);
printf("\n\n\t\t\tMis-");
sound(d/2);delay(200);nosound();delay(50);
printf("for-");
sound(d/2);delay(200);nosound();delay(50);
printf("tune");
sound(b);delay(200);nosound();delay(50);
printf(" Seemed");
sound(a);delay(200);nosound();delay(50);
printf(" His");
sound(g);delay(200);nosound();delay(50);
printf(" Lot");
sound(e);delay(700);nosound();delay(50);
printf("\n\n\t\t\tWe");
sound(e);delay(200);nosound();delay(50);
printf(" Got");
sound(e);delay(200);nosound();delay(50);
printf(" In");
sound(c);delay(200);nosound();delay(50);
printf(" To");
sound(b);delay(200);nosound();delay(50);
printf(" A");
sound(a);delay(200);nosound();delay(50);
printf(" Drift-");
sound(d);delay(200);nosound();delay(50);
printf("ed");
sound(d);delay(200);nosound();delay(50);
printf(" Bank");
sound(d);delay(200);nosound();delay(50);
printf("\n\n\t\t\tAnd");
sound(d);delay(200);nosound();delay(50);
printf(" Then");
sound(e*2);delay(200);nosound();delay(50);
printf(" We");
sound(d);delay(200);nosound();delay(50);
printf(" Got");
sound(c);delay(200);nosound();delay(50);
printf(" Up-");
sound(a);delay(200);nosound();delay(50);
printf("sot.");
sound(g);delay(450);nosound();delay(50);
printf(" Hey!");
sound(d);delay(450);nosound();delay(50);

clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tJin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(b);delay(200);nosound();delay(50);
printf(" Bells,");
sound(b);delay(450);nosound();delay(50);
printf(" Jin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(b);delay(200);nosound();delay(50);
printf(" Bells");
sound(b);delay(450);nosound();delay(50);
printf("\n\n\t\t\tJin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(d);delay(200);nosound();delay(50);
printf(" All");
sound(g);delay(325);nosound();delay(50);
printf(" the");
sound(a);delay(75);nosound();delay(50);
printf(" Way");
sound(b);delay(950);nosound();delay(50);
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tOh!");
sound(c);delay(200);nosound();delay(50);
printf(" What");
sound(c);delay(200);nosound();delay(50);
printf(" Fun!");
sound(c);delay(325);nosound();delay(50);
printf(" It");
sound(c);delay(75);nosound();delay(50);
printf(" Is");
sound(b);delay(200);nosound();delay(50);
printf(" To");
sound(b);delay(200);nosound();delay(50);
printf(" Ride");
sound(b);delay(200);nosound();delay(50);
printf("\n\n\t\t\tIn");
sound(b);delay(75);nosound();delay(50);
printf(" A");
sound(b);delay(75);nosound();delay(50);
printf(" One");
sound(a);delay(200);nosound();delay(50);
printf(" Horse");
sound(a);delay(200);nosound();delay(50);
printf(" Op-");
sound(a);delay(200);nosound();delay(50);
printf("en");
sound(b);delay(200);nosound();delay(50);
printf(" Sleigh,");
sound(a);delay(450);nosound();delay(50);
printf(" Yay!");
sound(d);delay(450);nosound();delay(50);
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tJin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(b);delay(200);nosound();delay(50);
printf(" Bells,");
sound(b);delay(450);nosound();delay(50);
printf(" Jin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(b);delay(200);nosound();delay(50);
printf(" Bells,");
sound(b);delay(450);nosound();delay(50);
printf("\n\n\t\t\tJin-");
sound(b);delay(200);nosound();delay(50);
printf("gle");
sound(d);delay(200);nosound();delay(50);
printf(" All");
sound(g);delay(325);nosound();delay(50);
printf(" the");
sound(a);delay(75);nosound();delay(50);
printf(" Way");
sound(b);delay(950);nosound();delay(50);
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tOh!");
sound(c);delay(200);nosound();delay(50);
printf(" What");
sound(c);delay(200);nosound();delay(50);
printf(" Fun!");
sound(c);delay(325);nosound();delay(50);
printf(" It");
sound(c);delay(75);nosound();delay(50);
printf(" Is");
sound(b);delay(200);nosound();delay(50);
printf(" To");
sound(b);delay(200);nosound();delay(50);
printf(" Ride");
sound(b);delay(200);nosound();delay(50);
printf("\n\n\t\t\tIn");
sound(b);delay(75);nosound();delay(50);
printf(" A");
sound(b);delay(75);nosound();delay(50);
printf(" One");
sound(d);delay(450);nosound();delay(50);
printf(" Horse");
sound(d);delay(450);nosound();delay(50);
printf(" Op-");
sound(c);delay(450);nosound();delay(50);
printf("en");
sound(a);delay(450);nosound();delay(50);
printf(" Sleigh!");
sound(g);delay(2250);nosound();delay(375);

clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\t\tTHE");
sound(d/2);delay(200);nosound();delay(50);
printf(" END");
sound(g);delay(200);nosound();delay(50);
delay(1500);
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t MERRY CHRISTMAS AND HAPPY NEW YEAR");
delay(4000);

//we wish u a merry christmas
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");

c=524;
d=293;
e=329;
f=369;
g=390;
a=440;
b=496;

printf("\n\n\n\n\t\t\tI");
sound(d);delay(450);nosound();delay(50);
printf(" Wish");
sound(g);delay(450);nosound();delay(50);
printf(" You");
sound(g);delay(200);nosound();delay(50);
printf(" A");
sound(a);delay(200);nosound();delay(50);
printf(" Mer-");
sound(g);delay(200);nosound();delay(50);
printf("rry");
sound(f);delay(200);nosound();delay(50);
printf(" Christ-");
sound(e);delay(450);nosound();delay(50);
printf("mas,");
sound(e);delay(450);nosound();delay(50);
printf("\n\n\t\t\tI");
sound(e);delay(450);nosound();delay(50);
printf(" Wish");
sound(a);delay(450);nosound();delay(50);
printf(" You");
sound(a);delay(200);nosound();delay(50);
printf(" A");
sound(b);delay(200);nosound();delay(50);
printf(" Mer-");
sound(a);delay(200);nosound();delay(50);
printf("rry");
sound(g);delay(200);nosound();delay(50);
printf(" Christ-");
sound(f);delay(450);nosound();delay(50);
printf("mas,");
sound(f);delay(450);nosound();delay(50);
printf("\n\n\n\n\t\t\tI");
sound(f);delay(450);nosound();delay(50);
printf(" Wish");
sound(b);delay(450);nosound();delay(50);
printf(" You");
sound(b);delay(200);nosound();delay(50);
printf(" A");
sound(c);delay(200);nosound();delay(50);
printf(" Mer-");
sound(b);delay(200);nosound();delay(50);
printf("rry");
sound(a);delay(200);nosound();delay(50);
printf(" Christ-");
sound(g);delay(450);nosound();delay(50);
printf("mas,");
sound(e);delay(450);nosound();delay(50);
printf("\n\n\t\t\tAnd");
sound(d);delay(200);nosound();delay(50);
printf(" A");
sound(d);delay(200);nosound();delay(50);
printf(" Hap-");
sound(e);delay(450);nosound();delay(50);
printf("py");
sound(a);delay(450);nosound();delay(50);
printf(" New");
sound(f);delay(450);nosound();delay(50);
printf(" Year!");
sound(g);delay(950);nosound();delay(50);
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tGlad");
sound(d);delay(450);nosound();delay(50);
printf(" Ti-");
sound(g);delay(450);nosound();delay(50);
printf("dings");
sound(g);delay(450);nosound();delay(50);
printf(" I");
sound(g);delay(450);nosound();delay(50);
printf(" Bring,");
sound(f);delay(950);nosound();delay(50);
printf("\n\n\t\t\tTo");
sound(f);delay(450);nosound();delay(50);
printf(" You");
sound(g);delay(450);nosound();delay(50);
printf(" And");
sound(f);delay(450);nosound();delay(50);
printf(" Your");
sound(e);delay(450);nosound();delay(50);
printf(" Kin.");
sound(d);delay(950);nosound();delay(50);
printf("\n\n\n\n\t\t\tI");
sound(a);delay(450);nosound();delay(50);
printf(" Wish");
sound(b);delay(450);nosound();delay(50);
printf(" You");
sound(a);delay(200);nosound();delay(50);
printf(" A");
sound(a);delay(200);nosound();delay(50);
printf(" Mer-");
sound(g);delay(200);nosound();delay(50);
printf("rry");
sound(g);delay(200);nosound();delay(50);
printf(" Christ-");
sound(2*d);delay(450);nosound();delay(50);
printf("mas,");
sound(d);delay(450);nosound();delay(50);
printf("\n\n\t\t\tAnd");
sound(d);delay(200);nosound();delay(50);
printf(" A");
sound(d);delay(200);nosound();delay(50);
printf(" Hap-");
sound(e);delay(450);nosound();delay(50);
printf("py");
sound(a);delay(450);nosound();delay(50);
printf(" New");
sound(f);delay(450);nosound();delay(50);
printf(" Year!");
sound(g);delay(950);nosound();delay(50);

clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tNow");
sound(d);delay(450);nosound();delay(50);
printf(" Bring");
sound(g);delay(700);nosound();delay(50);
printf(" Me");
sound(a);delay(200);nosound();delay(50);
printf(" Fig-");
sound(g);delay(200);nosound();delay(50);
printf("gy");
sound(f);delay(200);nosound();delay(50);
printf(" Pud-");
sound(e);delay(450);nosound();delay(50);
printf("ding,");
sound(e);delay(450);nosound();delay(50);
printf("\n\n\t\t\tNow");
sound(e);delay(450);nosound();delay(50);
printf(" Bring");
sound(a);delay(700);nosound();delay(50);
printf(" Me");
sound(b);delay(200);nosound();delay(50);
printf(" Fig-");
sound(a);delay(200);nosound();delay(50);
printf("gy");
sound(g);delay(200);nosound();delay(50);
printf(" Pud-");
sound(f);delay(450);nosound();delay(50);
printf("ding,");
sound(f);delay(450);nosound();delay(50);
printf("\n\n\n\n\t\t\tNow");
sound(f);delay(450);nosound();delay(50);
printf(" Bring");
sound(b);delay(700);nosound();delay(50);
printf(" Me");
sound(c);delay(200);nosound();delay(50);
printf(" Fig-");
sound(b);delay(200);nosound();delay(50);
printf("gy");
sound(a);delay(200);nosound();delay(50);
printf(" Pud-");
sound(g);delay(450);nosound();delay(50);
printf("ding,");
sound(e);delay(450);nosound();delay(50);
printf("\n\n\t\t\tAnd");
sound(d);delay(200);nosound();delay(50);
printf(" A");
sound(d);delay(200);nosound();delay(50);
printf(" Cup");
sound(e);delay(450);nosound();delay(50);
printf(" Of");
sound(a);delay(450);nosound();delay(50);
printf(" Good");
sound(f);delay(450);nosound();delay(50);
printf(" Cheer!");
sound(g);delay(950);nosound();delay(50);
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tGlad");
sound(d);delay(450);nosound();delay(50);
printf(" Ti-");
sound(g);delay(450);nosound();delay(50);
printf("dings");
sound(g);delay(450);nosound();delay(50);
printf(" I");
sound(g);delay(450);nosound();delay(50);
printf(" Bring,");
sound(f);delay(950);nosound();delay(50);
printf("\n\n\t\t\tTo");
sound(f);delay(450);nosound();delay(50);
printf(" You");
sound(g);delay(450);nosound();delay(50);
printf(" And");
sound(f);delay(450);nosound();delay(50);
printf(" Your");
sound(e);delay(450);nosound();delay(50);
printf(" Kin.");
sound(d);delay(950);nosound();delay(50);
printf("\n\n\n\n\t\t\tI");
sound(a);delay(450);nosound();delay(50);
printf(" Wish");
sound(b);delay(450);nosound();delay(50);
printf(" You");
sound(a);delay(200);nosound();delay(50);
printf(" A");
sound(a);delay(200);nosound();delay(50);
printf(" Mer-");
sound(g);delay(200);nosound();delay(50);
printf("rry");
sound(g);delay(200);nosound();delay(50);
printf(" Christ-");
sound(2*d);delay(450);nosound();delay(50);
printf("mas,");
sound(d);delay(450);nosound();delay(50);
printf("\n\n\t\t\tAnd");
sound(d);delay(200);nosound();delay(50);
printf(" A");
sound(d);delay(200);nosound();delay(50);
printf(" Hap-");
sound(e);delay(450);nosound();delay(50);
printf("py");
sound(a);delay(450);nosound();delay(50);
printf(" New");
sound(f);delay(450);nosound();delay(50);
printf(" Year!");
sound(g);delay(950);nosound();delay(50);

clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tI");
sound(d);delay(450);nosound();delay(50);
printf(" Won't");
sound(g);delay(450);nosound();delay(50);
printf(" Go");
sound(g);delay(200);nosound();delay(50);
printf(" Un-");
sound(a);delay(200);nosound();delay(50);
printf("til");
sound(g);delay(200);nosound();delay(50);
printf(" I");
sound(f);delay(200);nosound();delay(50);
printf(" Get");
sound(e);delay(450);nosound();delay(50);
printf(" Some");
sound(e);delay(450);nosound();delay(50);
printf("\n\n\t\t\tI");
sound(e);delay(450);nosound();delay(50);
printf(" Won't");
sound(a);delay(450);nosound();delay(50);
printf(" Go");
sound(a);delay(200);nosound();delay(50);
printf(" Un-");
sound(b);delay(200);nosound();delay(50);
printf("til");
sound(a);delay(200);nosound();delay(50);
printf(" I");
sound(g);delay(200);nosound();delay(50);
printf(" Get");
sound(f);delay(450);nosound();delay(50);
printf(" Some");
sound(f);delay(450);nosound();delay(50);
printf("\n\n\n\n\t\t\tI");
sound(f);delay(450);nosound();delay(50);
printf(" Won't");
sound(b);delay(450);nosound();delay(50);
printf(" Go");
sound(b);delay(200);nosound();delay(50);
printf(" Un-");
sound(c);delay(200);nosound();delay(50);
printf("til");
sound(b);delay(200);nosound();delay(50);
printf(" I");
sound(a);delay(200);nosound();delay(50);
printf(" Get");
sound(g);delay(450);nosound();delay(50);
printf(" Some");
sound(e);delay(450);nosound();delay(50);
printf("\n\n\t\t\tSo");
sound(d);delay(450);nosound();delay(50);
printf(" Bring");
sound(e);delay(450);nosound();delay(50);
printf(" It");
sound(a);delay(450);nosound();delay(50);
printf(" Out");
sound(f);delay(450);nosound();delay(50);
printf(" Here!");
sound(g);delay(950);nosound();delay(50);
clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tGlad");
sound(d);delay(450);nosound();delay(50);
printf(" Ti-");
sound(g);delay(450);nosound();delay(50);
printf("dings");
sound(g);delay(450);nosound();delay(50);
printf(" I");
sound(g);delay(450);nosound();delay(50);
printf(" Bring,");
sound(f);delay(950);nosound();delay(50);
printf("\n\n\t\t\tTo");
sound(f);delay(450);nosound();delay(50);
printf(" You");
sound(g);delay(450);nosound();delay(50);
printf(" And");
sound(f);delay(450);nosound();delay(50);
printf(" Your");
sound(e);delay(450);nosound();delay(50);
printf(" Kin.");
sound(d);delay(950);nosound();delay(50);
printf("\n\n\n\n\t\t\tI");
sound(a);delay(450);nosound();delay(50);
printf(" Wish");
sound(b);delay(450);nosound();delay(50);
printf(" You");
sound(a);delay(200);nosound();delay(50);
printf(" A");
sound(a);delay(200);nosound();delay(50);
printf(" Mer-");
sound(g);delay(200);nosound();delay(50);
printf("rry");
sound(g);delay(200);nosound();delay(50);
printf(" Christ-");
sound(2*d);delay(450);nosound();delay(50);
printf("mas,");
sound(d);delay(450);nosound();delay(50);
printf("\n\n\t\t\tAnd");
sound(d);delay(200);nosound();delay(50);
printf(" A");
sound(d);delay(200);nosound();delay(50);
printf(" Hap-");
sound(e);delay(450);nosound();delay(50);
printf("py");
sound(a);delay(450);nosound();delay(50);
printf(" New");
sound(f);delay(450);nosound();delay(50);
printf(" Year!");
sound(g);delay(950);nosound();delay(50);

clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tI");
sound(d);delay(450);nosound();delay(50);
printf(" Wish");
sound(g);delay(450);nosound();delay(50);
printf(" You");
sound(g);delay(200);nosound();delay(50);
printf(" A");
sound(a);delay(200);nosound();delay(50);
printf(" Mer-");
sound(g);delay(200);nosound();delay(50);
printf("rry");
sound(f);delay(200);nosound();delay(50);
printf(" Christ-");
sound(e);delay(450);nosound();delay(50);
printf("mas,");
sound(e);delay(450);nosound();delay(50);
printf("\n\n\t\t\tI");
sound(e);delay(450);nosound();delay(50);
printf(" Wish");
sound(a);delay(450);nosound();delay(50);
printf(" You");
sound(a);delay(200);nosound();delay(50);
printf(" A");
sound(b);delay(200);nosound();delay(50);
printf(" Mer-");
sound(a);delay(200);nosound();delay(50);
printf("rry");
sound(g);delay(200);nosound();delay(50);
printf(" Christ-");
sound(f);delay(450);nosound();delay(50);
printf("mas,");
sound(f);delay(450);nosound();delay(50);
printf("\n\n\n\n\t\t\tI");
sound(f);delay(450);nosound();delay(50);
printf(" Wish");
sound(b);delay(450);nosound();delay(50);
printf(" You");
sound(b);delay(200);nosound();delay(50);
printf(" A");
sound(c);delay(200);nosound();delay(50);
printf(" Mer-");
sound(b);delay(200);nosound();delay(50);
printf("rry");
sound(a);delay(200);nosound();delay(50);
printf(" Christ-");
sound(g);delay(450);nosound();delay(50);
printf("mas,");
sound(e);delay(450);nosound();delay(50);
printf("\n\n\t\t\tAnd");
sound(d);delay(200);nosound();delay(50);
printf(" A");
sound(d);delay(200);nosound();delay(50);
printf(" Hap-");
sound(e);delay(450);nosound();delay(50);
printf("py");
sound(a);delay(450);nosound();delay(50);
printf(" New");
sound(f);delay(450);nosound();delay(50);
printf(" Year!");
sound(g);delay(1450);nosound();delay(50);

clrscr();
printf("\n\n\t V.PREMKUMAR WISHES U A MERRY CHRISTMAS AND A HAPPY NEW YEAR");
printf("\n\n\n\n\t\t\tNow Gimme Me Ma Present! :D");
delay(5000);

}
